### ISSUE TITLE
Work Module Enhancements

### ISSUE THREAD

**Issue by matburt** [project-receptor/python-receptor#118]
`work.py` works on a basic level but some changes could make it much more usable and safe from out-of-control plugins. It can also provide a better framework for running plugins in.

- Run plugins under a concurrent.futures.Executor (ThreadPoolExecutor for example). This will allow us to track individual execution of the plugins:
  - Add a `cancel` contract instruction to a job invocation. This can be handled by a plugin by catching the thread stop exception.
  - A better manifest for presenting what's actually running for introspection through ping or status commands
- Abstract the return message queue and asyncio requirements from the plugin
  - Currently each plugin needs to implement it's own `asyncio.Queue` as that's what is expected to be returned from the execution method. Here we can give the plugin either it's own Queue to push into OR a general queue accessible from all worker contexts that can interleave responses.
  - Alternatively feeder Queues from each worker that feeds into a general response queue that delivers responses back.
- Better testing, performance, and resource usage of the `work.py` module
  - I'd love to be able to report overall resource usage, but on a basic level we need a mechanism for plugins to be able to inform Receptor how much work they are capable of. In the case of Ansible Runner this takes the form of how many cores and how much memory is available (in which case AWX uses that information to inform how many jobs can run).

**Comment by matburt** [comment]
This is implemented as per the design.

**Comment by jeremy-audet** [comment]
This issue seems to describe internal changes. If there's some technique for testing this issue, plase describe.

**Comment by ghjm** [comment]
This issue was to track work rather than to report a defect. I don't think it can be functionally verified.
