### ISSUE TITLE
Add event_loop fixture

### ISSUE THREAD

**Issue by psav** [project-receptor/python-receptor#29]
two pytest tests failing right now because event_loop fixture doesn't exist - thought there must be some kind of design around this so didn't want to make assumptions - just keeping here for tracking - would love to get all tests passing

**Comment by matburt** [comment]
This probably comes from pytest-asyncio which is in the pipfile here:

https://github.com/project-receptor/receptor/blob/master/Pipfile#L10

But isn't actually documented anywhere
