### ISSUE TITLE
Configuration infrastructure for plugins

### ISSUE THREAD

**Issue by ares** [project-receptor/python-receptor#30]
For upcoming Satellite plugin we need a way, how to configure receptor. Also in this case, we need multiple receptor instances on the same host. We need to specify following

* Satellite URL (probably localhost, but most likely we'll need to use FQDN due to SSL certificate)
* username
* password 
* path to Satellite certificate, path to CA (we generate self-signed certs, they don't have to be trusted)

We discussed two options - either we take care of it or receptor provides some standard way to do it. I'd prefer the later as there are other options that the plugin will need to take into consideration and that are coming from cloud.redhat.com side - live output (true/false), refresh interval (seconds).

Just to have a full picture of Satellite use-case. There is also a need for receptor configuration as well, it needs to be pointed to certificate/private key it uses when calling to cloud.redhat.com.

**Comment by psav** [comment]
So we are talking about how to set configuration for plugins as a whole? Do we have a global plugin conf system that is used by all plugins? or do we do something custom for each plugin?

**Comment by matburt** [comment]
I think this is already done in https://github.com/project-receptor/receptor/commit/4f8771dd5927d95fa9a59596dbfb4d7fc71b2447#diff-b59c76f86aa3e96ace7ad24e11cbf32b
